version: "3.8"

services:
  timescaledb:
    extends:
      file: ../base/docker-compose.yml
      service: application
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432/tcp"
    environment:
      POSTGRES_PASSWORD: xM8yRfInArr6121QRjn1
    volumes:
      - './postgres-data/:/var/lib/postgresql/data'
    networks:
      - timescaledb-network
    restart: unless-stopped
networks:
  timescaledb-network:
    driver: bridge